### PR TITLE
Splitting up the backend draw call to make it more flexible.

### PR DESCRIPTION
**Pull request by Zoomulator**
I'm experimenting with some design choices with a game prototype and kept bumping my head on the lifetime of the `&mut Graphics` given by the closure in `GlGraphics::draw`.
I can go into detail as to why, but my conclusion is that I need an `Rc<RefCell<_>>` to be able to pass it through a generalized trait without involving the lifetimes (turns out I probably need associated type constructors to solve my specific problem elegantly).

The problem boils down to this:
```rust
graphics.borrow_mut()
.draw(viewport, |c, _g| {
    // Things in the deeper systems call graphics.borrow_mut() resulting in a panic,
    // since the first line in this example holds its own mut borrow.
    app.draw_stuff(graphics, c);
}
```

It's easily fixed if the begin and end of the `GlGraphics::draw` are separated out and it's what this PR does.

```rust
let context = graphics.borrow_mut().draw_begin(viewport);
// The RefCell is not locked and subsystems are free to use it.
app.draw_stuff(graphics, context);
graphics.borrow_mut().draw_end();
```

The `draw` method remains and functions the same as before so this is not a breaking change.

I see the benefit of guaranteeing the begin and end via the closure but it also makes it less flexible in this case where you wish to put `GlGraphics` in a shared pointer.

### CODE REVIEW

**Comment by bvssvni** [comment]
Why don't you use the `g` parameter?

**Comment by Zoomulator** [comment]
In my specific problem, the `app` is a state machine with stored trait objects. It's a trait that I'd like to keep detached from the specifics of the Graphics trait. The `g` parameter is a `&mut  Graphics` that I can't pass through the state machine due to lifetime complications, so I need an `Rc<RefCell<Graphics>>` in order to poke through that layer.

**Comment by bvssvni** [comment]
I think this leads to overhead and might also confuse people.

Can you inherit `Graphics` with a new trait and implement the methods as a blanket impl?

For example:

```rust
pub trait GraphicsExt: Graphics { ... }
impl<T: Graphics> GraphicsExt for T { ... }
```

**Comment by bvssvni** [comment]
One advantage with Rust's type system is that you can add features this way in your project without needing to redesign the library.

**Comment by bvssvni** [comment]
Wait, I thought we needed RefCell in the library. Hmm...

**Comment by bvssvni** [comment]
Actually, I think this is a good idea. Merging.

**Comment by Zoomulator** [comment]
Great, thanks!

**Comment by bvssvni** [comment]
Thanks for contributing! I'll make a quick release so this won't have to wait for the next ecosystem update.

**Pull request merged**
