### PR TITLE
Removed Cargo features

### PR DESCRIPTION
**Pull request by bvssvni**
Closes https://github.com/PistonDevelopers/opengl_graphics/issues/208

- Bumped to 0.16.0 since breaking change

### CODE REVIEW

**Comment by bvssvni** [comment]
Anyone against this change? I would like to know if there is some good reason to keep the Cargo features...

**Comment by Phrohdoh** [comment]
I say let the applications pull in whatever they need instead of assuming they need these formats.

**Comment by bvssvni** [comment]
@Phrohdoh You can add the image to Cargo.toml and then tell it to only use PNG if you want to. This issue is about whether opengl_graphics should propagate these features, which might lead to confusion. I think such features should be avoided since there can be multiple dependency paths to the image library.

**Comment by Phrohdoh** [comment]
Okay, let me restate.
I agree with the removal as `opengl_graphics` ought to handle OpenGL, not other formats (in any means), IMO.

**Comment by bvssvni** [comment]
Ok. Merging.

**Comment by Potpourri** [comment]
@bvssvni Disable image features in higher level Cargo.toml  will not work, because for this crate need default features (all formats). Anyway compile image with all features not big problem. I agree with removal these features.

**Comment by bvssvni** [comment]
@Potpourri I thought setting `default-features = false` in a higher level would work. Should have tested this before merging. My mistake.

**Pull request merged**
